### PR TITLE
OP-544 fix some of the JRadioButton shortcut keys

### PR DESCRIPTION
**Pull request by dbmalkovsky**
This fixes `OperationEdit` and `PatientInsert` and only starts to touch on` PatientInsertExtended` which still has duplicated shortcut key issues.

See OP-544.

### CODE REVIEW

**Review by mwithi — APPROVED** [review]
LGTM. Thanks!

**Comment by mwithi** [comment]
I would wait to merge OP-523 before to proceed

**Comment by dbmalkovsky** [comment]
I am beginning to think that JRadioButtons shouldn't have shortcut keys at all; it is just too confusing especially in the large more complex dialogs.  What do you think?

**Comment by mwithi** [comment]
> I am beginning to think that JRadioButtons shouldn't have shortcut keys at all; it is just too confusing especially in the large more complex dialogs. What do you think?

I agree, let's have the shourcut for JButton(s) only

**Comment by dbmalkovsky** [comment]
I'm going to close this PR and replace it with a new one that removes the shortcuts for JRadioButtons.

**Pull request closed without merging**
