### PR TITLE
OP-403 Assign to visits instead of vsrows

### PR DESCRIPTION
**Pull request by dbmalkovsky**
This it a companion fix to the push to Core for OP-403.  See https://github.com/informatici/openhospital-core/pull/288

### CODE REVIEW

**Review by mwithi — CHANGES_REQUESTED** [review]
It seems it needs more deep analysis because vsRows would be not initialized and so here a NPE would be rised:
https://github.com/informatici/openhospital-gui/blob/2014404eae03fe776c418366891a349b219a9b3f/src/main/java/org/isf/visits/gui/VisitView.java#L350

**Comment by dbmalkovsky** [comment]
Fixed the NPE by removing `vsRows` definition and update; it was never queried.

**Comment by mwithi** [comment]
> Fixed the NPE by removing `vsRows` definition and update; it was never queried.

Fine. What about the compilation error reported at OP-403 ?

**Comment by dbmalkovsky** [comment]
@mwithi  I'm not seeing it; what exactly is it reporting and what version of the core jar are you using.  Note that the CI build is clean.

**Comment by mwithi** [comment]
> @mwithi I'm not seeing it; what exactly is it reporting and what version of the core jar are you using. Note that the CI build is clean.

It is clean because https://github.com/informatici/openhospital-core/pull/288 is not yet merged. I'm reporting that the two PR supposed to work together probably need a check https://openhospital.atlassian.net/browse/OP-403?focusedCommentId=12976
image

**Review by mwithi — APPROVED** [review]

**Pull request merged**
