### PR TITLE
[OP-128] adjustments

### PR DESCRIPTION
**Pull request by tomek39856**

### CODE REVIEW

**Comment by mwithi** [comment]
Hi @tomek39856, since we have new a new layout in the code and also a new default branch, is it possibile to rebase the work onto `develop`?

**Comment by tomek39856** [comment]
rebased to develop

**Comment by tomek39856** [comment]
sorry I broked formatting I'll fix it tommorow

**Comment by mwithi** [comment]
Is this PR meant to work with https://github.com/informatici/openhospital-core/pull/132? Because in this case we should first merge https://github.com/informatici/openhospital-core/pull/132 into develop, and then trying to adjust this, wdyt?

**Comment by tomek39856** [comment]
Yes exactly it's small fix for change of the way how quantity is calculated after jpa migration

**Comment by mwithi** [comment]
Superseded by https://github.com/informatici/openhospital-core/pull/132/commits/8c1dca52767860b24c3c6ddc78e0ce37bfb3698c

**Pull request closed without merging**
