### PR TITLE
Script updates

### PR DESCRIPTION
**Pull request by mizzioisf**
This should be - hopefully - the final iteration before 1.12 release.

New: Desktop shortcut creation with icon, working on Windows (tested on 11) and Linux (Mint 21.1)
New: Reads/writes settings from existing configuration files

- Simplified options and usage
- Reworked and reorganized code
- Fixed some bugs from the latest reviews

Needs testing :-)

### CODE REVIEW

**Comment by mwithi** [comment]
We have to solve once for all the problem of PORTABLE vs CLIENT... let's go for .ini? I think it's the best thing...

**Comment by mwithi** [comment]
PS: on my windows there is no icon, normal?
image

**Comment by mizzioisf** [comment]
> PS: on my Windows there is no icon, normal?
> 
> image

did you get the icon file from the PR also ?

**Comment by mizzioisf** [comment]
> We have to solve once for all the problem of PORTABLE vs CLIENT... let's go for .ini? I think it's the best thing...

It's there ! I set the mode in settings.properties directly.

**Comment by mwithi** [comment]
> > We have to solve once for all the problem of PORTABLE vs CLIENT... let's go for .ini? I think it's the best thing...
> 
> It's there ! I set the mode in settings.properties directly.

you're right! it works!

**Review by mwithi — APPROVED** [review]
LGTM. Thanks a lot!

**Pull request merged**
