### PR TITLE
OP-1096 Improve icons and images

### PR DESCRIPTION
**Pull request by mwithi**
See OP-1096.

### CODE REVIEW

**Review by dbmalkovsky — APPROVED** [review]
LGTM

**Review by mizzioisf — APPROVED** [review]
Very good, Let's merge !

**Comment by mwithi** [comment]
> Very good, Let's merge !

I'm still trying to improve the `logo_menu.png` and `logo_menu_vert.png` images

**Comment by mwithi** [comment]
Ready for review now

**Review by dbmalkovsky — APPROVED** [review]
LGTM if you accept the fact that this change requires more directories added to the classpath. 

Before it was:
<pre>
new ImageIcon("rsc" + File.separator + "images" + File.separator + "logo_menu_vert.png"
</pre>

and now it is 
<pre>
new ImageIcon(new ImageIcon(getClass().getClassLoader().getResource("logo_menu_vert.png"))
</pre>

which requires at least `/rsc/images` to be added to the classpath.

**Comment by mwithi** [comment]
> which requires at least `/rsc/images` to be added to the classpath.

yes, correct, but that

**Comment by mwithi** [comment]
@mizzioisf according with the hard-coded paths, we should tests the new icons also in terms of java classpath, could you do this test before we merge? Thanks

**Pull request merged**
