### PR TITLE
fix: workaround dcm4che repo service disruption

### PR DESCRIPTION
**Pull request by mwithi**
Temporary workaround for dcm4che servers disruption.

These disruptions are frequent. OP-347 is aimed to permanently solve this kind of issues by getting rid of dcm4che libraries.

**NOTE**: delete/move previous downloaded libs in your .m2 local repository

**WARNING**: This PR is linked to https://github.com/informatici/openhospital-core/pull/359 and so checks will fail if not merged first. Test it locally.

### CODE REVIEW

**Comment by mwithi** [comment]
@dbmalkovsky can you please check this? Thanks!

**Comment by dbmalkovsky** [comment]
@mwithi  Looks good

- Moved local repo out of the way
- Switched to your PR in the Core project
- Did a `mvn install`
- All was clean
- Switched to your PR in the GUI project
- Did a `mvn test`
- All was clean

**Comment by mwithi** [comment]
https://github.com/informatici/openhospital-core/pull/359 merged now

**Comment by mwithi** [comment]
Sorry @emecas I'm going to merge this without your review because the commits on develop are already ahead

**Pull request merged**
