### PR TITLE
OP-417 remove double assignment

### PR DESCRIPTION
**Pull request by dbmalkovsky**
Found with SpotBugs.    Remove double assignment as per OP-415.

### CODE REVIEW

**Comment by mwithi** [comment]
Checks are failing since https://github.com/informatici/openhospital-gui/commit/84fb862fb5eb8b84227beeefb380b5a9b0e0f86d.
I'm trying to understand the reason

**Comment by mwithi** [comment]
Sorry, the problem seems give by https://github.com/informatici/openhospital-core/commit/025b642f92ebdadd5f7cc78e435ab5af8967059a#diff-b2ad6341e919202cc833fe126a84d6bda0dd653cebd990ff59507c66bb70e966L50
Changes on 'core' should always be compiled with "gui" and "api"... my bad I didn't check. Could be enough to add back the empty constructor?

**Comment by dbmalkovsky** [comment]
Yes; the empty constructor is the problem.  I'll submit another PR if you want.

**Comment by dbmalkovsky** [comment]
See Core PR: https://github.com/informatici/openhospital-core/pull/310

Sorry about that....

**Comment by mwithi** [comment]
> See Core PR: [informatici/openhospital-core#310](https://github.com/informatici/openhospital-core/pull/310)
> 
> Sorry about that....

Thanks! NP, CI is in place for this 😄🙌

**Review by mwithi — APPROVED** [review]
Good catch!

**Pull request merged**
