### PR TITLE
OP-442 remove unread fields

### PR DESCRIPTION
**Pull request by dbmalkovsky**
See OP-442 for description of logic for removing the fields.

I also did some minor manual reformatting of the code without any other operational changes.

BTW, why is there a hardcoded FRENCH locale in this class?
````
final DateFormat currentDateFormat = DateFormat.getDateInstance(DateFormat.SHORT, Locale.FRENCH);
````

### CODE REVIEW

**Comment by mwithi** [comment]
> BTW, why is there a hardcoded FRENCH locale in this class?

Dirty code... can we replace with `getDateInstance(DateFormat.SHORT, new Locale(GeneralData.LANGUAGE))` ?

We could also remove all the following, in those method that are actually implemented
```
// TODO Auto-generated method stub
```

Only the `TODO ` keyword for the others that must be there empy for the interface

**Comment by dbmalkovsky** [comment]
Fixed the `Locale` and the `TODO`s.

**Comment by mwithi** [comment]
> Fixed the `Locale` and the `TODO`s.

Sorry I was hasty... I meant to remove the `TODO`s because there's nothing to do...

**Comment by dbmalkovsky** [comment]
`TODO`s removed.

**Comment by mwithi** [comment]
> `TODO`s removed.

Thanks a lot!

**Pull request merged**
