### PR TITLE
OP-917 fix rendering of Rectify button

### PR DESCRIPTION
**Pull request by dbmalkovsky**
See OP-917  this addresses only the Pharmacy → Pharmaceutical Stock Ward → Drugs [tab] after the New button is used.

This is a bit heavy handed but after trying multiple options of reevaluate, invalidate, repaint, resetting the column widths, etc. nothing else worked.

### CODE REVIEW

**Comment by mwithi** [comment]
I found something concerning that button that is strange, but sure could be optimized:
lines 516/517 and 1490/1491 and 1535/1536 are redundant...

maybe setting the viewport is the one rendering better the cellrenderers,
but maybe setting a cellrenderer again and again in other methods causes the glitch.

**Comment by dbmalkovsky** [comment]
I tried various combinations of commenting out the assignment of cell renderers and the problem still exists.   Guess my heavy handed approach is the one to go with.  Sorry.

**Comment by mwithi** [comment]
> I tried various combinations of commenting out the assignment of cell renderers and the problem still exists. Guess my heavy handed approach is the one to go with. Sorry.

There is another chance maybe: `jTableDrugs.setAutoCreateColumnsFromModel(false)` when we create the table, in this way should be enought to set the rendereres only once for all.

**Comment by dbmalkovsky** [comment]
@mwithi Nice find on `jTableDrugs.setAutoCreateColumnsFromModel(false)` is seems to work.  Thanks.

**Comment by mwithi** [comment]
> @mwithi Nice find on `jTableDrugs.setAutoCreateColumnsFromModel(false)` is seems to work. Thanks.

Do you think we can try also with removing the duplicated code above?

**Comment by dbmalkovsky** [comment]
The duplicated code is removed and things appear to function correctly.

**Comment by mwithi** [comment]
> The duplicated code is removed and things appear to function correctly.

wonderful! thanks a lot!

**Review by mwithi — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
